# Generated by Django 4.0.4 on 2022-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=300, null=True)),
                ('testName', models.CharField(max_length=300, null=True)),
                ('subjectName', models.CharField(max_length=300, null=True)),
                ('marks', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('examDate', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
