# Generated by Django 4.0.4 on 2022-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='courseId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='negativeMarking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examDate',
            field=models.DateTimeField(),
        ),
    ]
