# Generated by Django 4.0.4 on 2022-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_exam_courseid_exam_negativemarking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='courseId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='negativeMarking',
            field=models.IntegerField(),
        ),
    ]
