# Generated by Django 4.0.4 on 2022-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('optionA', models.CharField(max_length=200, null=True)),
                ('optionB', models.CharField(max_length=200, null=True)),
                ('optionC', models.CharField(max_length=200, null=True)),
                ('optionD', models.CharField(max_length=200, null=True)),
                ('correctAnswer', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
