# Generated by Django 4.0.4 on 2022-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_csv_files_questions_created_at_questions_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_files',
            name='csvFilePath',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
