# Generated by Django 4.0.4 on 2022-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_alter_csv_files_csvfilepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_files',
            name='importID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
