# Generated by Django 4.0.4 on 2022-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='negativeMarking',
            field=models.BooleanField(default=False),
        ),
    ]
