# Generated by Django 4.0.4 on 2022-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_negativemarking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='negativeMarking',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
