# Generated by Django 4.0.4 on 2022-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(null=True, verbose_name='ZipCode'),
        ),
    ]
