# Generated by Django 4.0.4 on 2022-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
    ]
