# Generated by Django 4.0.4 on 2022-05-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_email_toke_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_toke',
            new_name='email_token',
        ),
    ]
