# Generated by Django 4.0.4 on 2022-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_rename_email_toke_user_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.IntegerField(null=True),
        ),
    ]
