# Generated by Django 4.0.4 on 2022-05-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_user_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
