# Generated by Django 4.0.4 on 2022-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_user_is_admin_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
