# Generated by Django 4.0.4 on 2022-06-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_role_rename_date_joined_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
