# Generated by Django 4.0.4 on 2022-06-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
