# Generated by Django 4.0.4 on 2022-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_user_is_admin_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addharNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fees',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
