# Generated by Django 4.0.4 on 2022-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_user_addharnumber_user_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fees',
            field=models.CharField(max_length=200),
        ),
    ]
