# Generated by Django 4.0.4 on 2022-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_alter_user_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
