# Generated by Django 4.0.4 on 2022-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_user_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feesStatus',
            field=models.BooleanField(default=False),
        ),
    ]
