# Generated by Django 4.0.4 on 2022-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='duration',
            field=models.CharField(choices=[('Month', 30), ('Half Month', 15)], max_length=100, null=True),
        ),
    ]
