# Generated by Django 4.0.4 on 2022-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_customer_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='duration',
            field=models.CharField(choices=[('Month', '30 Days'), ('Half Month', '15 Days')], max_length=100, null=True),
        ),
    ]
