# Generated by Django 4.0.4 on 2022-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_customer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tiffin_start_date',
            field=models.DateField(null=True),
        ),
    ]
